on: [push]

jobs:
  hello_world_job:
    #runs-on: ubuntu-latest
    runs-on: arc-runner-set
    name: A job to say hello 2
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Hello world action step
        id: hello
        uses: ./
        with:
          who-to-greet: 'Mona the Octocat'
      # Use the output from the `hello` step
      - name: Wait
        run: sleep 5
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"

  arc_job:
    runs-on: arc-runner-set-docker-2
    name: Another job for Docker
    steps:
      - run: echo "🎉 This job uses runner scale set runners!"
      - uses: actions/checkout@v4
      - run: docker pull busybox
